apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculatepoint
  labels:
    app: calculatepoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculatepoint
  template:
    metadata:
      labels:
        app: calculatepoint
    spec:
      containers:
        - name: calculatepoint
          image: "minhyukchoi/calculatepoint:24101005"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
