apiVersion: apps/v1
kind: Deployment
metadata:
  name: walking history
  labels:
    app: walking history
spec:
  replicas: 1
  selector:
    matchLabels:
      app: walking history
  template:
    metadata:
      labels:
        app: walking history
    spec:
      containers:
        - name: walking history
          image: "username/walking history:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
