apiVersion: apps/v1
kind: Deployment
metadata:
  name: userwalkingstat
  labels:
    app: userwalkingstat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userwalkingstat
  template:
    metadata:
      labels:
        app: userwalkingstat
    spec:
      containers:
        - name: userwalkingstat
          image: "namahoon/userwalkingstat:24101001"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
