server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: walkinghistory
          uri: http://localhost:8082
          predicates:
            - Path=/walkingHsts/**, 
        - id: weather
          uri: http://localhost:8083
          predicates:
            - Path=/usrtFcstHsts/**, /weatherStnInfos/**, 
        - id: user
          uri: http://localhost:8084
          predicates:
            - Path=/users/**, 
        - id: userwalkingstat
          uri: http://localhost:8085
          predicates:
            - Path=/walkingStatByUsers/**, 
        - id: teamwalkingstat
          uri: http://localhost:8086
          predicates:
            - Path=/walkingStatByTeams/**, 
        - id: companywalkingstat
          uri: http://localhost:8087
          predicates:
            - Path=/walkingStatByCompanies/**, 
        - id: challenge
          uri: http://localhost:8088
          predicates:
            - Path=/challengeInfos/**, /challengeHsts/**, 
        - id: calculatepoint
          uri: http://localhost:8089
          predicates:
            - Path=/pointStandardInfos/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: walkinghistory
          uri: http://walkinghistory:8080
          predicates:
            - Path=/walkingHsts/**, 
        - id: weather
          uri: http://weather:8080
          predicates:
            - Path=/usrtFcstHsts/**, /weatherStnInfos/**, 
        - id: user
          uri: http://user:8080
          predicates:
            - Path=/users/**, 
        - id: userwalkingstat
          uri: http://userwalkingstat:8080
          predicates:
            - Path=/walkingStatByUsers/**, 
        - id: teamwalkingstat
          uri: http://teamwalkingstat:8080
          predicates:
            - Path=/walkingStatByTeams/**, 
        - id: companywalkingstat
          uri: http://companywalkingstat:8080
          predicates:
            - Path=/walkingStatByCompanies/**, 
        - id: challenge
          uri: http://challenge:8080
          predicates:
            - Path=/challengeInfos/**, /challengeHsts/**, 
        - id: calculatepoint
          uri: http://calculatepoint:8080
          predicates:
            - Path=/pointStandardInfos/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
