apiVersion: apps/v1
kind: Deployment
metadata:
  name: companywalkingstat
  labels:
    app: companywalkingstat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: companywalkingstat
  template:
    metadata:
      labels:
        app: companywalkingstat
    spec:
      containers:
        - name: companywalkingstat
          image: "username/companywalkingstat:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
