apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculate point
  labels:
    app: calculate point
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculate point
  template:
    metadata:
      labels:
        app: calculate point
    spec:
      containers:
        - name: calculate point
          image: "username/calculate point:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
