apiVersion: apps/v1
kind: Deployment
metadata:
  name: team walking stat
  labels:
    app: team walking stat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team walking stat
  template:
    metadata:
      labels:
        app: team walking stat
    spec:
      containers:
        - name: team walking stat
          image: "username/team walking stat:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
